---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    size: 4gb
    region: <%= ENV['DIGITAL_OCEAN_REGION'] %>
    attributes:
      postgres:
        version: "9.3"
  run_list:
  - recipe[apt]

suites:
  - name: default
    data_bags_path: data_bags
    run_list:
      - recipe[an_minimart::default]
    attributes: {}
